---
- name: install postgresql
  apt: name={{ item }} state=present
  with_items: [postgresql, postgresql-doc, postgresql-client, phppgadmin, python-psycopg2]
  tags: [install]

- name: listen on all interfaces
  lineinfile:
    dest: /etc/postgresql/9.4/main/postgresql.conf
    line: "listen_addresses = '*'			# what IP address(es) to listen on;"
    regexp: "^#?listen_addresses"
  notify: restart postgresql
  tags: [configure]

- name: start and enable postgresql
  service: name=postgresql state=started enabled=yes
  tags: [serve]

- name: open port 5432 in the firewall
  firewalld: service=postgresql state=enabled immediate=yes permanent=yes

- name: allow connections from webserver
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    line: "{{ item }}"
  with_items: "{{ postgresql_pg_hba_lines }}"
  notify: restart postgresql
  tags: [configure]

#- name: create a munin user
#  postgresql_user:
#    name: munin
#    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
#    state: present
#  tags: [configure]

- name: create a database dump directory
  file:
    path: /var/backups/postgresql
    state: directory
  tags: [install]

- name: perform a daily database dump
  copy:
    src: pg_dump_cronjob.sh
    dest: /etc/cron.daily/pg_dump_cronjob
    mode: 0755
  tags: [serve]
