---
- name: install postgresql
  apt: name={{ item }} state=present
  with_items: [postgresql, postgresql-doc, postgresql-client, phppgadmin]
  tags: [install]

#- name: install psycopg2
#  pacman: name=python2-psycopg2 state=present
#  tags: [install]

- name: start and enable postgresql
  service: name=postgresql state=started enabled=yes
  tags: [serve]

- name: open port 5432 in the firewall
  firewalld: service=postgresql state=enabled immediate=yes permanent=yes

#- name: create a munin user
#  postgresql_user:
#    name: munin
#    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
#    state: present
#  tags: [configure]
#
## Not sure if needs to add line in pg_hba.conf
## local all munin trust
