---
- name: check if the mailusers group exists on ipa server
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  command: ipa group-show mailusers
  register: group_show
  failed_when: group_show.rc == 1
  changed_when: false
  tags: [install]

- name: create the mailusers group
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  command: ipa group-add mailusers --desc "Mail User Group"
  when: group_show.rc != 0
  tags: [install]

- name: check if the mail mail service exists on ipa server
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  command: ipa service-show imap/{{ ansible_fqdn }}
  register: service_show
  failed_when: service_show.rc == 1
  changed_when: false
  tags: [install]

- name: create the mailusers group
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  command: ipa service-add imap/{{ ansible_fqdn }}
  when: service_show.rc != 0
  tags: [install]

- name: check if /etc/dovecot/krb5.keytab exists
  stat: path=/etc/dovecot/krb5.keytab
  register: keytab

- name: generate the host keytab
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  command: /usr/sbin/ipa-getkeytab -s {{ ipa_server }} -p imap/{{ ansible_fqdn }} -k /tmp/{{ ansible_hostname }}.keytab
  when: not keytab.stat.exists
  tags: [install]

- name: transfer the keytab over to the IPA client
  synchronize:
    src: /tmp/{{ ansible_hostname }}.keytab
    dest: /etc/dovecot/krb5.keytab
    archive: no
    ssh_args: -l root
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  when: not keytab.stat.exists
  notify: restart dovecot
  tags: [install]

- name: remove the keytab file on the FreeIPA server
  delegate_to: "{{ ipa_server }}"
  remote_user: ""
  become: no
  file:
    path: /tmp/{{ ansible_hostname }}.keytab
    state: absent
  tags: [install]

- name: make the keytab readable by dovecot
  file:
    path: /etc/dovecot/krb5.keytab
    mode: 0640
    group: dovecot
  tags: [install]
