---
- name: install dovecot
  apt: name={{ item }} state=present
  with_items: [dovecot-imapd, dovecot-lmtpd, dovecot-sieve]
  tags: [install]

- name: create the vmail user and home directory
  user:
    name: vmail
    createhome: yes
    home: "{{ dovecot_vmail_directory }}"
    shell: /usr/bin/false
  tags: [install]

#- name: add exim to the mail group
#  user:
#    name: exim
#    groups: mail
#    append: yes
#  tags: [install]

- name: configure dovecot specific options
  template:
    src: "{{ item }}.j2"
    dest: /etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
    - 15-mailboxes.conf
    - 20-lmtp.conf
    - 90-sieve.conf
  notify: restart dovecot
  tags: [configure]

- name: configure SSL certificate
  template:
    src: dovecot-openssl.cnf.j2
    dest: /etc/dovecot/dovecot-openssl.cnf
  register: sslconf
  tags: [configure]

- name: rename old SSL files
  command: 'mv "{{ item }}" "{{ item }}.old"'
  args:
    removes: "{{ item }}"
  when: sslconf.changed
  with_items:
  - /etc/dovecot/dovecot.pem
  - /etc/dovecot/private/dovecot.pem
  tags: [configure]

- name: make dovecot SSL certificate
  command: /usr/share/dovecot/mkcert.sh
  args:
    creates: /etc/dovecot/dovecot.pem
    chdir: /etc/dovecot
  notify: restart dovecot
  tags: [configure]

- name: enable imaps in firewalld
  firewalld: service=imaps state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: start and enable dovecot
  service: name=dovecot state=started enabled=yes
  tags: [serve]
