---
- name: install dovecot
  apt: name={{ item }} state=present
  with_items:
  - dovecot-imapd
  - dovecot-lmtpd
  - dovecot-sieve
  - dovecot-managesieved
  tags: [install]

- name: create the vmail user and home directory
  user:
    name: vmail
    createhome: yes
    home: "{{ dovecot_vmail_directory }}"
    shell: /usr/bin/false
  tags: [install]

- name: install the default sieve
  copy:
    src: default.sieve
    dest: /var/vmail/default.sieve
    owner: vmail
    group: vmail
  tags: [install]

- name: configure dovecot specific options
  template:
    src: "{{ item }}.j2"
    dest: /etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
    - 10-statistics.conf
    - 15-mailboxes.conf
    - 20-lmtp.conf
    - 90-sieve.conf
  notify: restart dovecot
  tags: [configure]

- name: configure SSL certificate
  template:
    src: dovecot-openssl.cnf.j2
    dest: /etc/dovecot/dovecot-openssl.cnf
  register: sslconf
  tags: [configure]

- name: rename old SSL files
  command: 'mv "{{ item }}" "{{ item }}.old"'
  args:
    removes: "{{ item }}"
  when: sslconf.changed
  with_items:
  - /etc/dovecot/dovecot.pem
  - /etc/dovecot/private/dovecot.pem
  tags: [configure]

- name: make dovecot SSL certificate
  command: /usr/share/dovecot/mkcert.sh
  args:
    creates: /etc/dovecot/dovecot.pem
    chdir: /etc/dovecot
  notify: restart dovecot
  tags: [configure]

- name: drop the sieve.xml firewalld service definition
  copy:
    src: sieve.xml
    dest: /etc/firewalld/services/sieve.xml
  register: sieve_service
  tags: [install]

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: sieve_service.changed
  tags: [install]

- name: enable the sieve service in firewalld
  firewalld: service=sieve state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: enable imaps in firewalld
  firewalld: service=imaps state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: start and enable dovecot
  service: name=dovecot state=started enabled=yes
  tags: [serve]
