---
- name: install dovecot
  pacman: name=dovecot state=present
  tags: [install]

- name: configure dovecot
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
  notify: restart dovecot
  tags: [configure]

- name: configure pam
  copy:
    src: dovecot.pam
    dest: /etc/pam.d/dovecot
  tags: [configure]

- name: configure SSL certificate
  template:
    src: dovecot-openssl.cnf.j2
    dest: /etc/ssl/dovecot-openssl.cnf
  notify: make dovecot SSL certificate
  tags: [configure]

- name: enable services in firewalld
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes
  with_items: [imap, imaps, pop3, pop3s]
  tags: [serve]

- name: start and enable dovecot
  service: name=dovecot state=started enabled=yes
  tags: [serve]
