---
- name: install nginx
  apt: name=nginx-full state=present
  tags: [install]

- name: write the default html document
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data

#- name: remove default server
#  file:
#    path: /etc/nginx/sites-enabled/default
#    state: absent
#  notify: reload nginx
#  tags: [configure]

#- name: configure the default proxy
#  template:
#    src: default_proxy.j2
#    dest: /etc/nginx/sites-available/default_proxy
#  notify: reload nginx
#  tags: [configure]

- name: configure the custom proxies
  template:
    src: reverse_proxy.j2
    dest: /etc/nginx/sites-available/{{ server.name }}
  with_items: "{{ nginx_proxy_servers }}"
  loop_control: {loop_var: server}
  notify: reload nginx
  tags: [configure]

#- name: enable the default proxy
#  file:
#    src: ../sites-available/default_proxy
#    dest: /etc/nginx/sites-enabled/default_proxy
#    state: link
#  notify: reload nginx
#  tags: [serve]

- name: enable the custom proxies
  file:
    src: ../sites-available/{{ server.name }}
    dest: /etc/nginx/sites-enabled/{{ server.name }}
    state: link
  with_items: "{{ nginx_proxy_servers }}"
  loop_control: {loop_var: server}
  notify: reload nginx
  tags: [serve]

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  tags: [serve]
