---
- name: install Java and other requirements
  apt:  
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-7-jre-headless
    - openjdk-7-jdk
    - pdsh

- name: create the hadoop group
  group:
    name: hadoop
    state: present

- name: create the hdfs user
  user:
    name: hdfs
    createhome: yes
    groups: hadoop
    shell: /bin/bash

- name: create the .ssh directory
  file:
    path: /home/hdfs/.ssh
    state: directory
    owner: hdfs
    group: hdfs
    mode: 0700

- name: copy the private ssh key
  copy:
    content: "{{ hadoop_ssh_private_key }}"
    dest: /home/hdfs/.ssh/id_rsa
    owner: hdfs
    mode: 0600

- name: copy the public ssh key and authorized_keys
  copy:
    content: "{{ hadoop_ssh_public_key }}"
    dest: /home/hdfs/.ssh/{{ item }}
    owner: hdfs
  with_items:
    - id_rsa.pub
    - authorized_keys

- name: download Hadoop
  unarchive:
    remote_src: yes
    src: http://apache.mirror.iweb.ca/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz
    dest: /opt
    creates: /opt/hadoop-{{ hadoop_version }}/bin/hadoop

- name: link hadoop to hadoop-2.x.x
  file:
    src: hadoop-{{ hadoop_version }}
    dest: /opt/hadoop
    state: link

- name: prepare the pid and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: hdfs
    group: hdfs
    mode: 0755
  with_items:
    - /var/hdfs/namenode
    - /var/hdfs/datanode

- name: prepare the log directory
  file:
    path: /var/log/hadoop
    state: directory
    owner: hdfs
    group: root
    mode: 0755

- name: edit configuration files
  template:
    src: "{{ item }}.j2"
    dest: /opt/hadoop/etc/hadoop/{{ item }}
  with_items:
    - hadoop-env.sh
    - core-site.xml
    - hdfs-site.xml

- name: set the bash rc file for hadoop
  copy:
    src: bashrc.hadoop
    dest: /home/hdfs/.bashrc.hadoop
    owner: hdfs
    group: hdfs

- name: source .bashrc.hadoop from .bashrc
  lineinfile:
    dest: /home/hdfs/.bashrc
    line: . ~/.bashrc.hadoop

- name: install hadoop.service
  copy:
    src: hadoop.service
    dest: /etc/systemd/system/hadoop.service
  register: hadoop_service

- name: format hdfs
  shell: /opt/hadoop/bin/hdfs namenode -format
  args:
    creates: /var/hdfs/namenode/current

- name: start and enable hadoop
  systemd:
    daemon_reload: yes
    name: hadoop
    state: started
    enabled: yes
