---
- name: install collectd
  apt:
    name: collectd-core
    state: present

- name: configure collectd
  template:
    src: collectd.conf
    dest: /etc/collectd/collectd.conf
  notify: restart collectd

- name: create the collectd.conf.d directory
  file:
    dest: /etc/collectd/collectd.conf.d
    state: directory

- name: configure the network plugin
  template:
    src: plugin-network.conf.j2
    dest: /etc/collectd/collectd.conf.d/network.conf
  notify: restart collectd

- name: start and enable collectd
  service:
    name: collectd
    state: started
    enabled: yes
