---
- name: set the localtime
  file:
    path: /etc/localtime
    state: link
    force: yes
    src: /usr/share/zoneinfo/America/Montreal

- name: enable en_CA.UTF-8 locale
  lineinfile:
    dest: /etc/locale.gen
    line: en_CA.UTF-8 UTF-8
    regexp: "^#?en_CA.UTF-8 UTF-8"
  notify: generate locales

- name: enable en_DK.UTF-8 locale
  lineinfile:
    dest: /etc/locale.gen
    line: en_DK.UTF-8 UTF-8
    regexp: "^#?en_DK.UTF-8 UTF-8"
  notify: generate locales

- name: setup locale
  copy:
    src: locale.conf
    dest: /etc/locale.conf

- name: configure vconsole
  copy:
    src: vconsole.conf
    dest: /etc/vconsole.conf

- name: install updatemirrors script
  copy:
    src: updatemirrors
    dest: /usr/local/bin/updatemirrors
    mode: 0744

- name: install packages
  pacman: name={{ item }} state=present
  with_items:
  - vim
  - sudo
  - tmux
  - git
  - findutils
  - mlocate
  - sysstat
  - strace
  - lsof
  - haveged
  - rsync
  - sysdig
  - linux-headers

- name: ensure gnu-netcat is not present
  pacman: name=gnu-netcat state=absent

- name: install networking tools
  pacman: name={{ item }} state=present
  with_items:
    - mtr
    - bind-tools
    - ethtool
    - net-tools
    - openbsd-netcat
    - nmap
    - iperf
    - dnstracer
    - tcpdump
    - ipcalc
    - iptraf-ng
    - traceroute

- name: start and enable sysstat
  service: name=sysstat state=started enabled=yes

- name: start and enable haveged
  service: name=haveged state=started enabled=yes

- name: configure search domains
  lineinfile:
    dest: /etc/systemd/resolved.conf
    line: Domains={{ bind_localdomain }}
    regexp: "^#?Domains="
  notify: restart systemd-resolved
