---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - mini-dinstall
  tags: [install]

- name: create the document root directory
  file:
    path: /var/www/debian/mini-dinstall/incoming
    state: directory
    owner: www-data
    group: www-data
  tags: [install]

- name: create the virtual host
  template:
    src: apt.conf.j2
    dest: /etc/apache2/sites-available/apt.conf
  tags: [install]

- name: enable the virtual host
  command: a2ensite apt
  args:
    creates: /etc/apache2/sites-enabled/apt.conf
  notify: restart apache
  tags: [serve]
