---
# Prerequisites to be done manually:
# - Setup networking
# - Set the hostname
#   hostnamectl set-hostname <hostname>
# - Install the python2 and openssh packages
# - Update the system (pacman -Syu)

- include: pacman-cache.yml

- hosts: home_network
  roles: [archlinux_system, firewalld]
