# Must install manually:
# - python2-dnf
---
- hosts: fedora
  tasks:

  - name: install packages
    dnf: name={{ item }} state=present
    with_items:
    - vim
    - python-firewall
    - tmux

  - name: execute ipa-backup daily
    cron:
      name: daily IPA backup
      hour: 4
      minute: 30
      job: /usr/sbin/ipa-backup
      #job: /usr/sbin/ipa-backup ipa-backup --quiet

- hosts: fedora
  roles: [borg-client]
