# Must install manually:
# - python2-dnf
---
- hosts: fedora
  tasks:

  - name: install packages
    dnf: name={{ item }} state=present
    with_items:
    - vim
    - python-firewall

  - name: enable PAM module mkhomedir
    lineinfile:
      dest: /etc/pam.d/system-auth
      line: "session     required      pam_mkhomedir.so umask=0022 skel=/etc/skel/"
      regexp: pam_mkhomedir
      insertbefore: "pam_keyinit"
