---
- hosts: nextcloud*

- hosts: mysql*
  tasks:
  - name: create the nextcloud database
    mysql_db:
      name: nextcloud
      state: present
  - name: create the nextcloud database user
    mysql_user:
      name: nextcloud
      host: "{{ nextcloud_db_user_host }}"
      password: "{{ nextcloud_db_password }}"
      priv: "nextcloud.*:ALL"
      state: present

- hosts: nextcloud*
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: nextcloud, tags: [nextcloud]}

- hosts: nginx.nyj004.deverteuil.net
  roles:
  - {role: reverse-proxy, tags: [reverse-proxy]}
  vars:
    nginx_proxy_servers:
    - name: nextcloud.deverteuil.net
      proxy_pass: "{{ hostvars['nextcloud.nyj004.deverteuil.net']['ansible_eth0']['ipv4']['address'] }}"
      ssl: yes
      additional_lines:
      - proxy_buffering off;
      - client_max_body_size 0;

- hosts: nginx.private.deverteuil.net
  roles:
  - {role: reverse-proxy, tags: [reverse-proxy]}
  vars:
    nginx_proxy_servers:
    - name: nextcloud.deverteuil.net
      proxy_pass: "{{ hostvars['nextcloud.private.deverteuil.net']['ansible_eth1']['ipv4']['address'] }}"
      ssl: yes
      additional_lines:
      - proxy_buffering off;
      - client_max_body_size 0;
