---
- hosts: nextcloud*

- hosts: mysql*
  tasks:
  - name: create the nextcloud database
    mysql_db:
      name: nextcloud
      state: present
  - name: create the nextcloud database user
    mysql_user:
      name: nextcloud
      host: "{{ nextcloud_db_user_host }}"
      password: "{{ nextcloud_db_password }}"
      priv: "nextcloud.*:ALL"
      state: present

- hosts: nextcloud*
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: nextcloud, tags: [nextcloud]}
