---
- hosts: dhcp-server
  roles: [archlinux_system, security, dhcp]

- hosts: resolvers

  tasks:
  - name: update localdomain zone file
    lineinfile:
      line: "{{ item.name }}  IN  A  {{ item.ip }}"
      dest: /var/named/{{ bind_localdomain }}.zone
      regexp: "^{{ item.name }} +IN +A "
    with_items: "{{ dhcp_static_hosts }}"
    notify: update localdomain zone serial

  handlers:
  - name: update localdomain zone serial
    lineinfile:
      regexp: "^ *\\d+ *; *Serial"
      line: "                                        {{ ansible_date_time.epoch }} ; Serial ({{ ansible_date_time.iso8601 }})"
      dest: /var/named/{{ bind_localdomain }}.zone
    notify: reload named
  - name: reload named
    service: name=named state=reloaded
