---
# usage: ansible-playbook --ask-vault-pass discard-vm.yml --extra-vars "name=<vm_name>"

- hosts: "{{ name }}"
  tasks:

  - name: Remove host from FreeIPA server.
    delegate_to: freeipa
    vars: {ansible_user: ""}
    become: no
    command: flock /tmp/ansible-lock ipa host-del {{ ansible_fqdn }}
    register: host_del
    changed_when: host_del.rc == 0
    failed_when: host_del.rc not in [0, 2]
    tags: [freeipa]

- hosts: localhost
  tasks:

  - name: grap VM XML
    virt:
      command: get_xml
      name: "{{ name }}"
    register: xml
    # <source file='/var/lib/libvirt/images/{{ name }}.qcow2'/>

  - name: hard shutdown the VM
    become: no
    virt:
      name: "{{ name }}"
      state: destroyed
      uri: qemu+ssh://fixion/system

  #TODO
  #- name: delete the storage
  #  delegate_to: fixion
  #  file:
  #    path: "{{ xml.stdout }}"
  #    state: absent

  - name: undefine the VM
    become: no
    virt:
      name: "{{ name }}"
      command: undefine
      uri: qemu+ssh://fixion/system
    #XXX This does not delete any volumes.
  
  - name: remove forward and reverse DNS entries
    shell: |
      nsupdate -k ~/lib/dnssec/dhcp_updater.conf << EOF
      del {{ hostvars[name]['ansible_fqdn'] }}
      del {{ hostvars[name]['ansible_default_ipv4']['address']|ipaddr('revdns') }}
      send

  - name: remove host from the inventory
    command: sed -i "/^[# ]*{{ name }}\>/d" {{ inventory_file }}

# Remove SSH known_hosts keys from local system.
# Remove forward and backward DNS entries.
# Remove the host from the inventory
