---
# usage: ansible-playbook --ask-vault-pass discard-vm.yml --extra-vars "name=<vm_name>"

- hosts: "{{ name }}"
  tasks:

  - name: Remove host from FreeIPA server.
    delegate_to: freeipa
    vars: {ansible_user: ""}
    become: no
    command: flock /tmp/ansible-lock ipa host-del {{ ansible_fqdn }}
    register: host_del
    changed_when: host_del.rc == 0
    failed_when: host_del.rc not in [0, 2]
    tags: [freeipa]

- hosts: localhost
  tasks:

  - name: hard shutdown the VM
    become: no
    virt:
      name: "{{ name }}"
      state: destroyed
      uri: qemu+ssh://fixion/system

  - name: undefine the VM
    become: no
    virt:
      name: "{{ name }}"
      command: undefine
      uri: qemu+ssh://fixion/system
    #XXX This does not delete any volumes.

# Remove SSH known_hosts keys from local system.
# Remove forward and backward DNS entries.
# Remove the host from the inventory
