---
# usage: ansible-playbook --ask-vault-pass discard-vm.yml --extra-vars "name=<vm_name>"

- hosts: "{{ name }}"
  tasks:

  - name: Remove host from FreeIPA server.
    delegate_to: freeipa
    vars: {ansible_user: ""}
    become: no
    command: flock /tmp/ansible-lock ipa host-del {{ ansible_fqdn }}
    register: host_del
    changed_when: host_del.rc == 0
    failed_when: host_del.rc not in [0, 2]
    tags: [freeipa]

# Remove host from FreeIPA server.
# Remove SSH known_hosts keys from local system.
# Hard shutdown the system.
# Delete the system from libvirtd.
# Remove forward and backward DNS entries.
# Remove the host from the inventory
