---
- name: deploy node_exporter
  hosts: home_network:nyc3
  roles:
    - {role: prometheus-node-exporter, tags: [prometheus-node-exporter]}

- name: deploy prometheus
  hosts: prometheus
  roles:
    - {role: prometheus, tags: [prometheus]}

- name: deploy Grafana
  hosts: grafana
  roles:
    - {role: grafana, tags: [grafana]}

- name: deploy telegraf
  hosts: home_network,nyc3
  roles:
  - {role: telegraf, tags: [telegraf]}

- name: deploy InfluxDB
  hosts: influxdb
  roles:
  - {role: influxdb, tags: [influxdb]}
