---
- hosts: postgresql
  tasks:
  - name: create the database
    become: yes
    become_user: postgres
    postgresql_db:
      name: zabbix_server
      state: present
    tags: [postgresql, install]

  - name: create the database user
    become: yes
    become_user: postgres
    postgresql_user:
      name: zabbix_server
      password: "{{ zabbix_database_password }}"
      db: zabbix_server
      priv: ALL
    tags: [postgresql, install]

- hosts: zabbix
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: zabbix, tags: [zabbix]}
