---
- name: deploy node_exporter
  hosts: all
  roles:
    - {role: prometheus-node-exporter, tags: [prometheus-node-exporter]}

- name: deploy prometheus
  hosts: prometheus
  roles:
    - {role: prometheus, tags: [prometheus]}

- name: deploy Grafana
  hosts: grafana
  roles:
    - {role: grafana, tags: [grafana]}
