---
- name: setup the database for Zabbix
  hosts: postgresql
  tasks:
  - name: create the database
    become: yes
    become_user: postgres
    postgresql_db:
      name: zabbix_server
      state: present
    tags: [postgresql, install]

  - name: create the database user
    become: yes
    become_user: postgres
    postgresql_user:
      name: zabbix_server
      password: "{{ zabbix_database_password }}"
      db: zabbix_server
      priv: ALL
    tags: [postgresql, install]

- name: install and configure zabbix-server
  hosts: zabbix
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: zabbix-server, tags: [zabbix-server]}

- name: deploy Zabbix agents
  hosts: home_network,nyc3
  roles:
  - {role: zabbix-agent, tags: [zabbix-agent]}

- name: deploy Grafana
  hosts: grafana
  roles:
  - {role: grafana, tags: [grafana]}

- name: deploy Graphite
  hosts: graphite
  roles:
  - {role: graphite, tags: [graphite]}

- name: deploy collectd
  hosts: home_network
  roles:
  - {role: collectd, tags: [collectd]}
