---
- name: deploy node_exporter
  hosts: all
  roles:
    - {role: prometheus-node-exporter, tags: [prometheus-node-exporter]}

- name: deploy Prometheus and Alertmanager
  hosts: prometheus
  roles:
    - {role: prometheus-alertmanager, tags: [alertmanager]}
    - {role: prometheus-blackbox-exporter, tags: [blackbox]}
    - {role: prometheus, tags: [prometheus]}

- name: deploy Grafana
  hosts: grafana
  roles:
    - {role: grafana, tags: [grafana]}
