---
- name: deploy Grafana
  hosts: grafana
  roles:
  - {role: grafana, tags: [grafana]}

- name: deploy telegraf
  hosts: home_network
  roles:
  - {role: telegraf, tags: [telegraf]}

- name: deploy InfluxDB
  hosts: influxdb
  roles:
  - {role: influxdb, tags: [influxdb]}
