---
- hosts: openvpn-server
  roles: [openvpn-server]
  vars:
    openvpn_key_params:
      country: "CA"
      province: "QC"
      city: "Verdun"
      org: "deVerteuil.net"
      email: "alexandre@deverteuil.net"
      ou: ""
