---
- hosts: pacman-cache
  roles: [archlinux_system, security, pacman-cache, nfs]
  vars:
    nfs_exports:
    - path: /var/cache/pacman
      dirname: pacman
      hosts: [[192.168.13.0/24, "rw,no_root_squash"]]
  # Format of nfs_exports items:
  # - path: /path/name/to/share
  #   dirname: exported_dirname
  #   hosts: [192.168.13.0/24, ro]

- hosts: home_network:!pacman-cache
  roles: [pacman-cache-client, nfs]
  vars:
    nfs_mounts:
    - what: "pacman-cache.private.deverteuil.net:/pacman"
      where: /var/cache/pacman
  # Format of nfs_mounts items:
  # - what: "host:/path"
  #   where: /path/to/mountpoint
