---
# Prerequisites to be done manually:
# - Setup networking
# - Set the hostname
#   hostnamectl set-hostname <hostname>
# - Install the python2 and openssh packages
# - Update the system (pacman -Syu)

- hosts: pacman-cache
  roles: [pacman-cache, firewalld, ftpd]
- hosts: home_network:!pacman-cache
  roles: [pacman-cache-client]
- hosts: home_network
  roles: [common, firewalld]
- hosts: hypervisor
  roles: [hypervisor]
- hosts: nameservers
  roles: [named]
- hosts: dhcp-server
  roles: [dhcp]
- hosts: unifi
  roles: [unifi]
- hosts: tor
  roles: [tor_node]
- hosts: mailservers
  roles: [mailserver]
- hosts: fixion
  roles: [timeserver]
- hosts: home_network:!fixion
  roles: [systemd-timesyncd]
- hosts: home_network
  roles: [freeipa-client]
  serial: 1
- hosts: [home_network]
  roles: [munin-node]
- hosts: munin
  roles: [webserver, munin-master]
- hosts: borg
  roles: [backup-server]
- hosts: home_network
  roles: [backup-client]
- hosts: [dovecot]
  roles: [service_dovecot]
- hosts: openvpn-server
  roles: [openvpn-server, router]
