---
# Prerequisites to be done manually:
# - Setup networking
# - Set the hostname
#   hostnamectl set-hostname <hostname>
# - Install the python2 and openssh packages
# - Update the system (pacman -Syu)

- hosts: fixion
  roles:
  - {role: timeserver, tags: [timeserver]}
- hosts: home_network:!fixion
  roles:
  - {role: systemd-timesyncd, tags: [systemd-timesyncd]}
  remote_user: root
- hosts: home_network
  roles:
  - {role: common, tags: [common]}
  - {role: freeipa-client, tags: [freeipa-client]}
  serial: 1
  remote_user: root
- hosts: pacman-cache
  roles:
  - {role: pacman-cache, tags: [pacman-cache]}
  - {role: firewalld, tags: [firewalld]}
  - {role: ftpd, tags: [ftpd]}
- hosts: home_network:!pacman-cache
  roles:
  - {role: pacman-cache-client, tags: [pacman-cache-client]}
- hosts: borg
  roles:
  - {role: backup-server, tags: [backup-server]}
- hosts: home_network
  roles:
  - {role: firewalld, tags: [firewalld]}
  - {role: munin-node, tags: [munin-node]}
  - {role: backup-client, tags: [backup-client]}
- hosts: hypervisor
  roles:
  - {role: hypervisor, tags: [hypervisor]}
- hosts: nameservers
  roles:
  - {role: named, tags: [named]}
- hosts: dhcp-server
  roles:
  - {role: dhcp, tags: [dhcp]}
- hosts: unifi
  roles:
  - {role: unifi, tags: [unifi]}
- hosts: tor
  roles:
  - {role: tor_node, tags: [tor_node]}
- hosts: mailservers
  roles:
  - {role: mailserver, tags: [mailserver]}
  - {role: dovecot, tags: [dovecot]}
- hosts: munin
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: munin-master, tags: [munin-master]}
- hosts: openvpn-server
  roles:
  - {role: openvpn-server, tags: [openvpn-server]}
  - {role: router, tags: [router]}
