---
- hosts: mysql,postgresql
  tasks:
  - name: gather database servers IP addresses
    setup:
      filter: ansible_eth0

- hosts: web
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: kanboard, tags: [kanboard]}
  # Hosts all web services on the secure interface (secure VLAN)
  # over http only.

- hosts: grafana
  tasks:
  - name: gather facts
    setup:
      filter: "ansible_eth*"

- hosts: nginx
  roles:
  - {role: reverse-proxy, tags: [reverse-proxy]}
  # acquires all the SSL certificates
  # Does SSL offloading.
  # Proxies everything except /.well-known/acme-challenge/
  # certbot acquires SSL certificates using webroot
  # Eventually should also proxy SMTP and IMAP.
  # Needs ports 80, 443 and eventually SMTPS and IMAPS ports open.

- hosts: haproxy
  roles:
    - {role: haproxy, tags: [haproxy]}
    - {role: prometheus-haproxy-exporter, tags: [haproxy-exporter]}
