---
- hosts: mysql,postgresql
  tasks:
  - name: gather database servers IP addresses
    setup:
      filter: ansible_eth1

- hosts: web
  roles:
  - {role: webserver, tags: [webserver]}
  - {role: kanboard, tags: [kanboard]}
  # Hosts all web services on the secure interface (secure VLAN)
  # over http only.

- hosts: nginx
  roles:
  - {role: reverse-proxy, tags: [reverse-proxy]}
  - {role: letsencrypt, tags: [letsencrypt]}
  # acquires all the SSL certificates
  # Does SSL offloading.
  # Proxies everything except /.well-known/acme-challenge/
  # certbot acquires SSL certificates using webroot
  # Eventually should also proxy SMTP and IMAP.
  # Needs ports 80, 443 and eventually SMTPS and IMAPS ports open.
