---
- name: install munin-node
  pacman: name=munin-node state=present

- name: copy ssh key
  authorized_key:
    user: munin
    key: "{{ munin_ssh_public_key }}"

- name: configure munin-node
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
  notify: restart munin-node

- name: configure the smart plugins
  copy:
    src: smart
    dest: /etc/munin/plugin-conf.d/smart

- name: configure the exim plugins
  copy:
    src: exim
    dest: /etc/munin/plugin-conf.d/exim

- name: auto-enable plugins
  shell: munin-node-configure --shell | sh
  notify: restart munin-node
  args:
    creates: /etc/munin/plugins/df

- name: allow TCP port for munin-node
  copy:
    src: 20-munin-node
    dest: /etc/iptables/rules.d/20-munin-node

- name: assemble iptables.rules
  assemble:
    dest: /etc/iptables/iptables.rules
    src: /etc/iptables/rules.d
  notify: reload iptables

- name: start and enable munin-node
  service: name=munin-node state=started enabled=yes

- name: add the host to munin.conf on the munin master
  delegate_to: munin
  template:
    src: munin.conf.j2
    dest: /etc/munin/munin-conf.d/{{ ansible_hostname }}.conf
