---
- name: install exim
  pacman: name=exim state=present
  tags: [install]

- name: create the /etc/mail/private directory
  file:
    path: /etc/mail/private
    mode: 0700
    owner: exim
    group: exim
    state: directory

- name: create the self-signed SSL certificate
  command: openssl req -x509 -newkey rsa:1024 -keyout /etc/mail/private/exim.pem -out /etc/mail/private/exim.pem -days 9999 -nodes
  args:
    creates: /etc/mail/private/exim.pem
  notify: reload exim
  tags: [configure]

- name: configure exim
  template:
    src: exim.conf.j2
    dest: /etc/mail/exim.conf
  notify: reload exim
  tags: [configure]

- include: spamassassin.yml
  when: exim_install_spamassassin

- name: update aliases
  template:
    src: aliases.j2
    dest: /etc/mail/aliases
  notify: run newaliases
  tags: [configure]

- name: enable service smtp in firewalld
  firewalld: service=smtp state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: drop the submission.xml firewalld service definition
  copy:
    src: submission.xml
    dest: /etc/firewalld/services/submission.xml
  register: submission_service
  tags: [install]

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: submission_service.changed
  tags: [install]

- name: enable the submission service in firewalld
  firewalld: service=submission state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: start and enable exim
  service: name=exim state=started enabled=yes
  tags: [serve]
