---
- name: install the exim4-daemon-heavy package
  apt: name=exim4-daemon-heavy state=present
  notify: restart exim4

- name: configure Exim4
  template:
    src: exim4.conf.j2
    dest: /etc/exim4/exim4.conf
  notify: reload exim4
  tags: [configure]

- include: spamassassin.yml
  when: exim_install_spamassassin

#- name: update aliases
#  template:
#    src: aliases.j2
#    dest: /etc/mail/aliases
#  notify: run newaliases
#  tags: [configure]

- name: enable service smtp in firewalld
  firewalld: service=smtp state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: drop the submission.xml firewalld service definition
  copy:
    src: submission.xml
    dest: /etc/firewalld/services/submission.xml
  register: submission_service
  tags: [install]

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: submission_service.changed
  tags: [install]

- name: enable the submission service in firewalld
  firewalld: service=submission state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: start and enable exim4
  service: name=exim4 state=started enabled=yes
  tags: [serve]
