---
- name: install the exim4-daemon-heavy package
  apt: name=exim4-daemon-heavy state=present
  notify: restart exim4

- name: configure Exim4
  template:
    src: exim4.conf.j2
    dest: /etc/exim4/exim4.conf
  notify: reload exim4
  tags: [configure]

- name: add Debian-exim to the mail group
  # to access /var/run/dovecot/auth-client
  user:
    name: Debian-exim
    groups: mail
    append: yes
  notify: reload exim4
  tags: [install]

- name: enable service smtp in firewalld
  firewalld: service=smtp state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: drop the submission.xml firewalld service definition
  copy:
    src: submission.xml
    dest: /etc/firewalld/services/submission.xml
  register: submission_service
  tags: [install]

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: submission_service.changed
  tags: [install]

- name: enable the submission service in firewalld
  firewalld: service=submission state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: start and enable exim4
  service: name=exim4 state=started enabled=yes
  tags: [serve]

- name: use OpenDNS resolvers
  lineinfile:
    dest: /etc/network/interfaces
    line: "        dns-nameservers 208.67.222.222 208.67.220.220"
    regexp: dns-nameservers
    insertafter: iface eth0 inet static
  when: "{{ exim_use_opendns }}"
  notify: restart networking
  tags: [configure]

- name: allow zabbix to run monitoring commands
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/zabbix-exim
  tags: [configure]

- name: create the zabbix_agentd.conf.d directory
  file:
    state: directory
    path: /etc/zabbix/zabbix_agentd.conf.d
  tags: [configure]

- name: create zabbix user parameters
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf.d/exim.conf
  tags: [configure]
