---
- name: install exim
  pacman: name=exim state=present

- name: configure exim
  template:
    src: exim.conf.j2
    dest: /etc/mail/exim.conf
  notify: reload exim

- include: spamassassin.yml
  when: exim_install_spamassassin

- name: update aliases
  template:
    src: aliases.j2
    dest: /etc/mail/aliases
  notify: run newaliases

- name: enable service smtp in firewalld
  firewalld: service=smtp state=enabled permanent=yes immediate=yes

- name: start and enable exim
  service: name=exim state=started enabled=yes
