---
- name: install spamassassin
  apt: name={{ item }} state=present
  with_items: [spamassassin, spamc]
  tags: [install]

- name: update spamassassin rules
  command: /usr/bin/vendor_perl/sa-update
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc in [0, 3]
  # From the source code of /usr/bin/vendor_perl/sa-update:
  #   0: updates found and successfully applied
  #   1: no updates were needed (success with nothing to do)
  #   2: lint of site pre files failed, cannot continue
  #   3: some failures, but at least one channel suceeded
  #   4 or higher means all channels failed
  tags: [configure]

- name: start and enable spamassassin
  service: name=spamassassin state=started enabled=true
  tags: [serve]

- name: install teach-spam
  copy:
    src: teach-spam
    dest: /usr/local/bin/teach-spam
    mode: 0744
    owner: vmail
    group: vmail
  tags: [install]

- name: install teach-spam timer and service
  copy:
    src: teach-spam.{{ item }}
    dest: /etc/systemd/system/teach-spam.{{ item }}
  with_items: [service, timer]
  tags: [install]

- name: start and enable teach-spam.timer
  service: name=teach-spam.timer state=started enabled=yes
  tags: [serve]
