---
- name: install iptables
  pacman: name=iptables state=present

- name: create iptables directories
  file:
    path: /etc/iptables/rules.d
    state: directory

- name: install base iptables template
  template:
    src: "{{ item }}-base.j2"
    dest: /etc/iptables/rules.d/{{ item }}-base
  with_items: ["00", 99]
  notify: reload iptables

- name: install vars iptables template
  template:
    src: 10-ansible_vars.j2
    dest: /etc/iptables/rules.d/10-ansible_vars
  when: iptables_allow_ports != []
  notify: reload iptables

- name: assemble iptables.rules
  assemble:
    dest: /etc/iptables/iptables.rules
    src: /etc/iptables/rules.d
  notify: reload iptables

- name: start and enable iptables
  service: name=iptables state=started enabled=yes

- name: install sudo
  pacman: name=sudo state=present
