---
- name: create cron jobs
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute|default(omit) }}"
    hour: "{{ item.hour|default(omit) }}"
    day: "{{ item.day|default(omit) }}"
    month: "{{ item.month|default(omit) }}"
    weekday: "{{ item.weekday|default(omit) }}"
    special_time: "{{ item.special_time|default(omit) }}"
    disabled: "{{ item.disabled|default(omit) }}"
    state: "{{ item.state|default(omit) }}"
    user: "{{ item.user|default(omit) }}"
  with_items: "{{ miscellaneous_cronjobs }}"
