---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - libvirt-daemon-system
  - virt-goodies
  - virt-what
  - virt-top
  - virt-manager
  - libguestfs-tools
  tags: [install]

- name: start and enable hypervisor
  service: name=libvirtd state=started enabled=yes
  tags: [serve]

- name: exclude VM images from backups
  copy:
    src: backup_filter
    dest: /var/lib/libvirt/.backup
  tags: [configure]

- name: enable nested KVM
  lineinfile:
    line: options kvm_intel nested=1
    dest: /etc/modprobe.d/qemu-system-x86.conf
    create: yes
