---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - libvirt-daemon-system
  - virt-goodies
  - virt-what
  - virt-top
  - virt-manager
  tags: [install]

- name: start and enable hypervisor
  service: name=libvirtd state=started enabled=yes
  tags: [serve]

- name: exclude VM images from backups
  copy:
    src: backup_filter
    dest: /var/lib/libvirt/.backup
  tags: [configure]

- name: don't run switched packets through netfilter
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
  with_items:
  - net.bridge.bridge-nf-call-ip6tables
  - net.bridge.bridge-nf-call-arptables
  - net.bridge.bridge-nf-call-iptables
