---
- name: create /etc/zabbix/.my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/zabbix/.my.cnf
    mode: 0660
    group: zabbix

- name: create the MySQL user for zabbix-agent
  mysql_user:
    name: zabbix-agent
    password: "{{ zabbix_agent_mysql_password }}"

- name: configure MySQL items
  template:
    src: userparameter_mysql.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf.d/userparameter_mysql.conf
  notify: restart zabbix-agent
