---
letsencrypt_email: webmaster@{{ ansible_fqdn }}
letsencrypt_certificates: []
letsencrypt_http_01_port: 54321
letsencrypt_staging: no

haproxy_check_updated_certs_weekday: "*"
haproxy_check_updated_certs_hour: 23
haproxy_check_updated_certs_minute: 0
