---
- name: install openvpn
  apt: name=openvpn state=present
  tags: [install]

- name: create a directory for status files
  file:
    dest: /var/local/openvpn-status
    state: directory

- name: copy make easy-rsa certificate authority
  command: make-cadir openvpn
  args:
    chdir: /root
    creates: /root/openvpn
  tags: [install]

- name: configure easy-rsa vars
  template:
    src: vars.j2
    dest: /root/openvpn/vars
  tags: [configure]

- name: configure openvpn
  template:
    src: server.conf.j2
    dest: /etc/openvpn/{{ item.name }}.conf
  with_items: "{{ openvpn_configs }}"
  notify: restart openvpn
  tags: [configure]

- name: copy sample client configuration file
  copy:
    src: client.conf.sample
    dest: /root/client.conf.sample
  tags: [configure]

- name: enable openvpn
  service: name=openvpn enabled=yes
  tags: [serve]

- name: check if the server certificate exists
  stat: path=/root/openvpn/keys/openvpn-server.crt
  register: crt
  tags: [serve]

- name: start openvpn server
  service: name=openvpn state=started
  when: crt.stat.exists
  tags: [serve]

- name: enable service openvpn in firewalld
  firewalld: service=openvpn state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: configure the collectd plugin
  template:
    src: collectd-openvpn.conf.j2
    dest: /etc/collectd/collectd.conf.d/openvpn.conf
  notify: restart collectd
