---
- name: install requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnuplot-nox

- name: install opentsdb
  apt:
    deb: https://github.com/OpenTSDB/opentsdb/releases/download/v2.3.0/opentsdb-2.3.0_all.deb
    state: present

- name: configure opentsdb
  template:
    src: opentsdb.conf.j2
    dest: /etc/opentsdb/opentsdb.conf
  notify: restart opentsdb

- name: start and enable opentsdb
  service:
    name: opentsdb
    state: started
    enabled: yes

- name: open port 4242
  firewalld:
    port: 4242/tcp
    state: enabled
    permanent: yes
    immediate: yes
