---
- name: install dhcp
  pacman: name=dhcp state=present

- name: configure dhcp
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf
  notify: restart dhcpd

- name: start and enable dhcpd
  service: name=dhcpd4 state=started enabled=yes

- name: let dhcp through the firewall
  firewalld: service=dhcp state=enabled permanent=yes immediate=yes
