---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - mariadb-server
  - python-mysqldb
  tags: [install]

- name: start and enable mysql
  service: name=mysql state=started enabled=yes
  tags: [serve]

- name: set root MySQL password
  mysql_user:
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
  tags: [install]

- name: save the root MySQL password in .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
  tags: [install]
