---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - mariadb-server
  - python-mysqldb
  tags: [install]

- name: start and enable mysql
  service: name=mysql state=started enabled=yes
  tags: [serve]

- name: set root MySQL password
  mysql_user:
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
  tags: [install]

- name: set the bind address
  lineinfile:
    dest: /etc/mysql/my.cnf
    line: bind-address            = {{ mysql_bind_address }}
    regexp: "^bind-address"
  notify: restart mysql
  tags: [configure]

- name: save the root MySQL password in .my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600
  tags: [install]

- name: open the MySQL TCP port
  firewalld: service=mysql state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: create a backup directory for database dumps
  file:
    path: /var/backups/mysql
    state: directory
  tags: [install]

- name: perform a daily database dump
  copy:
    src: mysqldump_cronjob.sh
    dest: /etc/cron.daily/mysqldump
    mode: 0755
  tags: [serve]
