---
- name: install unifi
  pacman: name=unifi state=present

## Runs as user unifi, can't bind priviledged port.
#- name: serve UI on port 443
#  lineinfile:
#    line: unifi.https.port=443
#    dest: /usr/lib/unifi/data/system.properties
#  notify: restart unifi

- name: copy unifi service file for firewalld
  copy:
    src: unifi.xml
    dest: /etc/firewalld/services/unifi.xml
  register: service_unifi

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: service_unifi.changed

- name: enable service unifi in firewalld
  firewalld: service=unifi state=enabled permanent=yes immediate=yes

- name: start and enable unifi
  service: name=unifi state=started enabled=yes
