---
- name: add GPG key for unifi repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C0A52C50
  tags: [install]

- name: add the unifi repository
  apt_repository:
    repo: deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti
    state: present
  tags: [install]

- name: install unifi
  apt: name=unifi state=present
  tags: [install]

## Runs as user unifi, can't bind priviledged port.
#- name: serve UI on port 443
#  lineinfile:
#    line: unifi.https.port=443
#    dest: /usr/lib/unifi/data/system.properties
#  notify: restart unifi

- name: copy unifi service file for firewalld
  copy:
    src: unifi.xml
    dest: /etc/firewalld/services/unifi.xml
  register: service_unifi
  tags: [install]

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: service_unifi.changed
  tags: [install]

- name: enable service unifi in firewalld
  firewalld: service=unifi state=enabled permanent=yes immediate=yes
  tags: [serve]

- name: forward http and httpd ports
  command: firewall-cmd {{ item }} --add-forward-port=port=443:proto=tcp:toport=8443
  register: forward
  changed_when: '"ALREADY_ENABLED" not in forward.stdout'
  with_items: ["", --permanent]
  tags: [serve]

- name: start and enable unifi
  service: name=unifi state=started enabled=yes
  tags: [serve]
