---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - php5-pgsql
  - zabbix-proxy-pgsql
  tags: [install]

- name: create the database schema and import initial data
  shell: cd /usr/share/zabbix-proxy-pgsql && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && psql -h {{ zabbix_database_server }} -U zabbix_proxy -d zabbix_proxy -f schema.sql && touch /etc/zabbix/schema.done
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: "{{ zabbix_database_password }}"
  tags: [install]

- name: configure zabbix-proxy
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    mode: 0660
  notify: restart zabbix-proxy
  tags: [configure]

- name: enable zabbix-proxy
  lineinfile:
    dest: /etc/default/zabbix-proxy
    line: START=yes
    regexp: ^START
  notify: restart zabbix-proxy
  tags: [serve]

- name: start and enable zabbix-proxy
  service: name=zabbix-proxy state=started enabled=yes
  tags: [serve]
