---
- name: install bind
  pacman: name=bind state=present

- name: configure bind
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
  notify: reload bind

- name: install minimal localdomain zone file
  template:
    src: localdomain.zone.j2
    dest: /var/named/{{ bind_localdomain }}.zone
    force: no
  notify: reload bind

- name: install minimal localdomain rDNS zone file
  template:
    src: rdns.zone.j2
    dest: /var/named/13.168.192.in-addr.arpa.zone
    force: no
  notify: reload bind

- name: start and enable bind
  service: name=named state=started enabled=yes

- name: open dns port
  copy:
    src: 20-dns
    dest: /etc/iptables/rules.d/20-dns

- name: assemble iptables.rules
  assemble:
    dest: /etc/iptables/iptables.rules
    src: /etc/iptables/rules.d
  notify: reload iptables

- name: configure systemd-resolved
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
  notify: restart systemd-resolved
