---
- name: install bind
  pacman: name=bind state=present

- name: configure bind
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    mode: 0640
    owner: root
    group: named
  notify: restart bind

- name: start and enable bind
  service: name=named state=started enabled=yes

- name: open dns port
  copy:
    src: 20-dns
    dest: /etc/iptables/rules.d/20-dns

- name: assemble iptables.rules
  assemble:
    dest: /etc/iptables/iptables.rules
    src: /etc/iptables/rules.d
  notify: reload iptables
