---
- name: update exim4 configuration
  command: update-exim4.conf

- name: restart exim4
  service: name=exim4 state=restarted

- name: run locale-gen
  command: locale-gen

- name: update grub configuration
  command: update-grub
