---
- name: install tor
  pacman: name=tor state=present

- name: install arm (Anonymizing Relay Monitor)
  pacman: name=arm state=present

- name: configure tor
  template:
    dest: /etc/tor/torrc
    backup: yes
    src: torrc.j2
  notify:
  - reload tor

- name: copy tor service file for firewalld
  copy:
    src: tor.xml
    dest: /etc/firewalld/services/tor.xml
  register: service_tor

- name: reload firewalld
  service: name=firewalld state=reloaded
  when: service_tor.changed

- name: enable tor service in firewalld
  firewalld: service=tor state=enabled permanent=yes immediate=yes

- name: enable and start tor
  service: name=tor state=started enabled=yes
