---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - bridge-utils
  tags: [install]

- name: load the bridge module at boot time
  lineinfile:
    dest: /etc/modules-load.d/ansible-role-bridge.conf
    line: bridge
    create: yes
    state: present

- name: don't run switched packets through netfilter
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/ansible-role-bridge.conf
  with_items:
  - net.bridge.bridge-nf-call-ip6tables
  - net.bridge.bridge-nf-call-arptables
  - net.bridge.bridge-nf-call-iptables
