---
- name: create the alex user
  user:
    name: alex
    password: $6$rounds=656000$eaRXjtMikusX6NnD$HN6d1W6Sjv65hAiIBRMkFdM7pl4/0UPLK.sRSvRkHNlmsfptTybFEUSx/7wRyfiWj/TT9trA3IKa2WAsmHZ7X/
    update_password: on_create

- name: add group wheel to the alex user
  user:
    name: alex
    groups: wheel
    append: yes
  when: ansible_distribution != "Ubuntu"

- name: add group sudo to the alex user
  user:
    name: alex
    groups: sudo
    append: yes
  when: ansible_distribution == "Ubuntu"

- name: add group systemd-journal to the alex user
  user:
    name: alex
    groups: systemd-journal
    append: yes
  when: ansible_distribution == "Archlinux"

- name: create the home directory structure
  become: yes
  file: 
    path: /home/alex/{{ item }}
    state: directory
    mode: 0700
  with_items: [bin, lib, mnt, src, tmp, var, wip]

- name: create the public directories in home
  become: yes
  file:
    path: /home/alex/pub/{{ item }}
    state: directory
    mode: 0755
  with_items: [musique, vidéo, images, texte]

- name: create symlinks to version controlled dotfiles
  become: yes
  file:
    path: /home/alex/.{{ item }}
    state: link
    src: src/dotfiles/{{ item }}
    force: yes
  with_items: [vim, vimrc, Xdefaults, gitconfig, tmux.conf]

- name: add higg's key to the known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    key: higgs ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE0git4tAjyjx8NLKw5hY6MBRmgsTWCsEGIneW0/7gq/rv9JhgegAaYpbzS8nPJWP6VcuShK9sKMFnXxZYnwU/U=
    name: higgs
  when: ansible_hostname != "higgs"

- name: add alexdev.chickenkiller.com's key to the known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    key: alexdev.chickenkiller.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE0git4tAjyjx8NLKw5hY6MBRmgsTWCsEGIneW0/7gq/rv9JhgegAaYpbzS8nPJWP6VcuShK9sKMFnXxZYnwU/U=
    name: alexdev.chickenkiller.com
  when: ansible_hostname != "higgs"

- name: ensure git is installed on Archlinux
  pacman: name=git state=present
  when: ansible_distribution == "Archlinux"

- name: ensure git is installed on Ubuntu
  apt: name=git state=present
  when: ansible_distribution == "Ubuntu"

- name: ensure git is installed on CentOS
  yum: name=git state=present
  when: ansible_distribution == "CentOS"
