---
- name: install Java and other requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-7-jre-headless
    - openjdk-7-jdk
    - pdsh
    - liblzo2-2

- name: create the hadoop group
  group:
    name: hadoop
    state: present

- name: create the hbase user
  user:
    name: hbase
    createhome: yes
    groups: hadoop
    shell: /bin/bash

- name: create the .ssh directory
  file:
    path: /home/hbase/.ssh
    state: directory
    owner: hbase
    group: hbase
    mode: 0700

- name: copy the private ssh key
  copy:
    content: "{{ hadoop_ssh_private_key }}"
    dest: /home/hbase/.ssh/id_rsa
    owner: hbase
    mode: 0600

- name: copy the public ssh key and authorized_keys
  copy:
    content: "{{ hadoop_ssh_public_key }}"
    dest: /home/hbase/.ssh/{{ item }}
    owner: hbase
  with_items:
    - id_rsa.pub
    - authorized_keys

- name: download HBase
  unarchive:
    remote_src: yes
    src: http://apache.mirror.iweb.ca/hbase/{{ hbase_version }}/hbase-{{ hbase_version }}-bin.tar.gz
    dest: /opt
    creates: /opt/hbase-{{ hbase_version }}/bin/hbase

- name: link /opt/hbase to hbase-1.x.x
  file:
    src: hbase-{{ hbase_version }}
    dest: /opt/hbase
    state: link

- name: prepare the zookeeper data directory
  file:
    path: /var/zookeeper
    state: directory
    owner: hbase
    group: hbase
    mode: 0755

- name: prepare the log directory
  file:
    path: /var/log/hbase
    state: directory
    owner: hbase
    group: root
    mode: 0755

- name: configure hbase
  template:
    src: "{{ item }}.j2"
    dest: /opt/hbase/conf/{{ item }}
  with_items:
    - hbase-env.sh
    - hbase-site.xml

- name: set the bashrc file for hbase
  copy:
    src: bashrc.hbase
    dest: /home/hbase/.bashrc.hbase
    owner: hbase
    group: hbase

- name: source .bashrc.hbase from .bashrc
  lineinfile:
    dest: /home/hbase/.bashrc
    line: . ~/.bashrc.hbase

- name: create a directory to link to native libraries
  file:
    dest: /opt/hbase/lib/native
    state: directory

- name: link to the Hadoop native libraries
  file:
    dest: /opt/hbase/lib/native/Linux-amd64-64
    src: /opt/hadoop/lib/native
    state: link

- name: create the /hbase directory in hdfs
  shell: <
    sudo -u hdfs /opt/hadoop/bin/hdfs dfs -mkdir /hbase &&
    sudo -u hdfs /opt/hadoop/bin/hdfs dfs -chown hbase:hbase /hbase &&
    touch /opt/hbase/conf/.hdfs-directory-created
  args:
    creates: /opt/hbase/conf/.hdfs-directory-created

- name: install hbase.service
  copy:
    src: hbase.service
    dest: /etc/systemd/system/hbase.service

- name: start and enable hbase
  systemd:
    daemon_reload: yes
    name: hbase
    state: started
    enabled: yes
