---
- name: install graphite-carbon
  apt:
    name: graphite-carbon
    state: present

- name: configure Carbon
  template:
    src: "{{ item }}.j2"
    dest: /etc/carbon/{{ item }}
  with_items:
    - carbon.conf
    - storage-schemas.conf

- name: enable carbon-cache
  lineinfile:
    dest: /etc/default/graphite-carbon
    line: CARBON_CACHE_ENABLED=true
    regexp: ^CARBON_CACHE_ENABLED=
    state: present

- name: start and enable carbon-cache
  service:
    name: carbon-cache
    state: started
    enabled: yes

- name: open port 2003
  firewalld:
    port: 2003/tcp
    state: enabled
    permanent: yes
    immediate: yes
