---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: enable mod_wsgi
  apache2_module:
    name: wsgi
    state: present
  notify: restart apache2

- name: start and enable apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: create the graphite virtualhost
  template:
    src: apache2-graphite.conf.j2
    dest: /etc/apache2/sites-available/graphite.conf

- name: enable the graphite virtualhost
  file:
    dest: /etc/apache2/sites-enabled/graphite.conf
    src: ../sites-available/graphite.conf
    state: link
  notify: reload apache2

- name: disable the default virtualhost
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload apache2

- name: open ports http and https
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  with_items:
    - http
    - https
