---
- name: generate ssh keys for root
  command: ssh-keygen -N "" -f /root/.ssh/id_rsa
  args:
    creates: /root/.ssh/id_rsa.pub

- name: read the public key
  command: cat /root/.ssh/id_rsa.pub
  register: pubkey
  changed_when: false

- name: install the public key on the attic server
  delegate_to: attic
  authorized_key:
    user: attic
    key: "{{ pubkey.stdout }}"
    key_options: 'command="/usr/local/bin/attic_serve.sh",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc'

- name: install attic
  apt: name=attic state=present

- name: copy attic.exclude
  template:
    src: attic.exclude.j2
    dest: /etc/attic.exclude

- name: copy attic_create_archive.sh
  template:
    dest: /usr/local/bin/attic_create_archive.sh
    src: attic_create_archive.sh
    mode: 0744

- name: create a cron job
  cron:
    name: attic create
    cron_file: /etc/crontab
    user: root
    minute: "{{ attic_cron_create_minute }}"
    hour: "{{ attic_cron_create_hour }}"
    job: /usr/local/bin/attic_create_archive.sh
