---
grafana_admin_user: admin
grafana_admin_password: admin
grafana_ldap_enabled: false
grafana_ldap_host: 127.0.0.1
grafana_ldap_bind_dn: cn=admin,dc=grafana,dc=org
grafana_ldap_bind_password: grafana
grafana_ldap_search_filter: (cn=%s)
grafana_ldap_search_base_dns: ["dc=grafana,dc=org"]
grafana_ldap_attribute_name: givenName
grafana_ldap_attribute_surname: sn
grafana_ldap_attribute_username: cn
grafana_ldap_attribute_member_of: memberOf
grafana_ldap_attribute_email: email
grafana_ldap_default_org_id: 1
grafana_ldap_group_mappings:
- group_dn: cn=admins,dc=grafana,dc=org
  org_role: Admin
  org_id: 1  # Default: grafana_ldap_default_org_id
- group_dn: cn=users,dc=grafana,dc=org
  org_role: Editor
- group_dn: "*"
  org_role: Viewer
