---
- name: configure package repository mirrors
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    update_cache: "{{ item.update_cache }}"
    mode: 644
  with_items:
  - {repo: "deb-src http://debian.mirror.iweb.ca/debian/ jessie main",         state: "{{ common_deb_src_repos }}", update_cache: no}
  - {repo: "deb-src http://security.debian.org/ jessie/updates main",          state: "{{ common_deb_src_repos }}", update_cache: no}
  - {repo: "deb-src http://debian.mirror.iweb.ca/debian/ jessie-updates main", state: "{{ common_deb_src_repos }}", update_cache: no}
  - {repo: "deb http://httpredir.debian.org/debian/ jessie main",              state: present, update_cache: no}
  - {repo: "deb http://httpredir.debian.org/debian/ jessie-updates main",      state: present, update_cache: no}
  - {repo: "deb http://debian.mirror.iweb.ca/debian/ jessie main",             state: absent, update_cache: no}
  - {repo: "deb http://debian.mirror.iweb.ca/debian/ jessie-updates main",     state: absent, update_cache: yes}
  tags: [configure]

- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - firewalld
  - vim
  - sudo
  - tmux
  - git
  - sysstat
  - haveged
  - rsync
  - strace
  - tree
  - curl
  #- sysdig
  #- linux-headers
  tags: [install]

- name: install networking tools
  apt: name={{ item }} state=present
  with_items:
    - mtr
    - ethtool
    - net-tools
    - nmap
    - iperf
    - dnstracer
    - tcpdump
    - ipcalc
  tags: [install]

- name: start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - sysstat
  - haveged
  - firewalld
  tags: [serve]

- name: create /var/log/lastlog
  # I don't want to touch it if it already exists
  # so I use the command rather than the file module.
  # Using copy scans terabytes of sparse zeroes for
  # comparison with an empty content.
  command: touch /var/log/lastlog
  args:
    creates: /var/log/lastlog
  tags: [configure]

- name: ensure proper permissions and ownership for lastlog
  file:
    path: /var/log/lastlog
    state: file
    group: utmp
    mode: 0644
  tags: [configure]

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717217
- name: fix UDP checksum error
  command: firewall-cmd {{ item }} --direct --add-rule ipv4 mangle POSTROUTING 0 -p udp --dport bootps -j CHECKSUM --checksum-fill
  register: direct
  changed_when: '"ALREADY_ENABLED" not in direct.stdout'
  with_items: ["", --permanent]
  tags: [serve]

- name: configure exim4
  template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
  notify:
  - update exim4 configuration
  - restart exim4
  tags: [configure]

- name: set email to send root mail to
  lineinfile:
    dest: /etc/aliases
    line: "root: {{ exim_root_alias }}"
    regexp: ^root

- name: generate locales
  lineinfile:
    dest: /etc/locale.gen
    line: "{{ item }}"
    regexp: ^[# ]*{{ item }}
  with_items:
  - en_CA.UTF-8 UTF-8
  - en_DK.UTF-8 UTF-8
  - en_US.UTF-8 UTF-8
  - fr_CA.UTF-8 UTF-8
  notify: run locale-gen
  tags: [configure]

- name: customize bash prompt
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d/{{ item }}
  with_items:
  - prompt_command.sh
  - less.sh
  - prompt.sh
  tags: [configure]

- name: force color prompt in skel/.bashrc
  lineinfile:
    dest: /etc/skel/.bashrc
    line: force_color_prompt=yes
    regexp: ^#force_color_prompt=yes
  tags: [configure]

- name: remove motd
  file:
    path: /etc/motd
    state: absent
  tags: [configure]

- name: force colour prompt
  lineinfile:
    dest: /etc/skel/.bashrc
    line: force_color_prompt=yes
    regexp: ^#force_color_prompt
  tags: [configure]
