---
- name: install abs
  pacman: name=abs state=present

- name: install base-devel packages
  pacman: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - flex
    - gcc
    - groff
    - libtool
    - m4
    - make
    - patch
    - pkg-config

- name: configure pacman to clean only outdated packages
  lineinfile:
    line: CleanMethod = KeepCurrent
    regexp: CleanMethod
    dest: /etc/pacman.conf
