---
- name: install packages
  pacman: name={{ item }} state=present
  with_items:
    - abs
    - vsftpd

- name: install base-devel packages
  pacman: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - flex
    - gcc
    - groff
    - libtool
    - m4
    - make
    - patch
    - pkg-config

- name: configure pacman to clean only outdated packages
  lineinfile:
    line: CleanMethod = KeepCurrent
    regexp: CleanMethod
    dest: /etc/pacman.conf

- name: create a directory for the local repository
  file:
    dest: /srv/ftp/archlinux
    state: directory

- name: serve anonymous users
  lineinfile:
    dest: /etc/vsftpd.conf
    line: "{{ item }}"
  with_items:
  - anon_root=/srv/ftp
  - no_anon_password=YES
  notify: reload vsftpd

- name: start and enable vsftpd
  service: name=vsftpd state=started enabled=yes

- name: open port 21
  copy:
    src: 20-ftpd
    dest: /etc/iptables/rules.d

- name: assemble iptables.rules
  assemble:
    dest: /etc/iptables/iptables.rules
    src: /etc/iptables/rules.d
  notify: reload iptables
