---
- name: restart exim4
  service: name=exim4 state=restarted

- name: reload exim4
  service: name=exim4 state=reloaded

- name: run newaliases
  command: newaliases

- name: restart networking
  service: name=networking state=restarted
