---
- name: stop and disable scollector
  systemd:
    name: scollector
    state: stopped
    enabled: no
    daemon_reload: yes
  ignore_errors: yes

- name: remove the stats user
  user:
    name: stats
    state: absent

- name: remove scollector.service
  file:
    dest: /etc/systemd/system/scollector.service
    state: absent

- name: remove scollector
  file:
    path: /opt/scollector
    state: absent

