---
- name: create the installation directory
  file:
    path: /opt/scollector/collectors/0
    state: directory

- name: install scollector
  get_url:
    url: https://github.com/bosun-monitor/bosun/releases/download/0.6.0-beta1/scollector-linux-amd64
    dest: /opt/scollector/scollector
    mode: 0755

- name: create the stats user
  user:
    name: stats
    createhome: no
    comment: Metrics collector
    state: present

- name: configure scollector
  template:
    src: scollector.toml.j2
    dest: /opt/scollector/scollector.toml
  notify: restart scollector

- name: install scollector.service
  copy:
    src: scollector.service
    dest: /etc/systemd/system/scollector.service

- name: start scollector
  systemd:
    name: scollector
    state: started
    enabled: yes
    daemon_reload: yes
