---
- name: install packages
  apt: name={{ item }} state=present
  with_items:
  - task-web-server
  - php5
  - php5-mysql
  - php5-gd
  - php5-pgsql
  - php5-curl
  #- mod_wsgi
  #- python-virtualenv
  #- perl-libwww  # For the Munin apache plugins
  #- lynx  # For apachectl status
  notify: restart apache2
  tags: [install]

- name: write the default VirtualHost index page
  copy:
    src: index.html
    dest: /var/www/html/index.html
  tags: [configure]

- name: customize the default VirtualHosts
  template:
    src: "{{ item }}.j2"
    dest: /etc/apache2/sites-available/{{ item }}
  with_items: [000-default.conf, default-ssl.conf]
  notify: restart apache2
  tags: [configure]

- name: enable apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
  - ssl
  - remoteip
  - rewrite
  notify: restart apache2
  tags: [configure]

- name: configure mod_remoteip
  copy:
    src: remoteip.conf
    dest: /etc/apache2/mods-enabled/remoteip.conf
  notify: restart apache2
  tags: [configure]

- name: log remote client's IP address
  lineinfile:
    dest: /etc/apache2/apache2.conf
    # Change %h for %a
    line: 'LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined'
    regexp: '^LogFormat ".*" combined$'
  notify: restart apache2
  tags: [configure]

- name: enable the SSLHonorCipherOrder directive
  lineinfile:
    dest: /etc/apache2/mods-available/ssl.conf
    line: "	SSLHonorCipherOrder on"
    regexp: "^\\s*#?SSLHonorCipherOrder"
  notify: restart apache2
  tags: [configure]

- name: enable the site default-ssl
  command: a2ensite default-ssl
  args:
    creates: /etc/apache2/sites-enabled/default-ssl.conf
  notify: restart apache2
  tags: [configure]

- name: enable http and https services in firewalld
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes
  with_items: [http, https]
  tags: [serve]
