---
- name: install packages
  pacman: name={{ item }} state=present
  with_items:
  - apache
  - mod_wsgi
  - python-virtualenv
  - perl-libwww  # For the Munin apache plugins
  - lynx  # For apachectl status
  tags: [install]

- name: set ServerAdmin directive
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: ServerAdmin {{ webserver_serveradmin }}
    regexp: ^#?ServerAdmin.*$
  notify: restart apache
  tags: [configure]

- name: create the conf.d directory
  file:
    dest: /etc/httpd/conf.d
    state: directory
  tags: [install]

- name: include the files in conf.d
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: IncludeOptional conf.d/*.conf
  notify: restart httpd
  tags: [configure]

- include: ssl.yml
- include: vhosts.yml
- include: wsgi.yml
- include: status.yml

- name: enable http and https services in firewalld
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes
  with_items: [http, https]
  tags: [serve]
