---
- name: install packages
  pacman: name={{ item }} state=present
  with_items:
  - apache
  - mod_wsgi
  - python-virtualenv
  - perl-libwww  # For the Munin apache plugins
  - lynx  # For apachectl status

- name: set ServerAdmin directive
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: ServerAdmin {{ webserver_serveradmin }}
    regexp: ^#?ServerAdmin.*$
  notify: restart apache

- name: create the conf.d directory
  file:
    dest: /etc/httpd/conf.d
    state: directory

- include: ssl.yml
- include: vhosts.yml
- include: wsgi.yml
- include: status.yml

- name: open http and https ports
  copy:
    src: 20-webserver
    dest: /etc/iptables/rules.d/20-webserver
  notify: reload iptables
