---
- name: uninstall ntpd
  pacman: name=ntp state=absent
  tags: [install]

- name: configure systemd-timesyncd
  copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
  notify: restart systemd-timesyncd
  tags: [configure]

- name: start and enable systemd-timesyncd
  service: name=systemd-timesyncd state=started enabled=true
  tags: [serve]
