---
- name: uninstall ntpd
  pacman: name=ntp state=absent

- name: configure systemd-timesyncd
  copy:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
  notify: restart systemd-timesyncd

- name: start and enable systemd-timesyncd
  service: name=systemd-timesyncd state=started enabled=true
