---
- name: install letsencrypt client
  pacman: name=letsencrypt state=present

- name: create a webroot for letsencrypt
  file:
    path: "{{ letsencrypt_webroot }}"
    state: directory
    owner: http
    group: http
    mode: 0750

#- name: configure letsencrypt
#  template:
#    src: cli.ini.j2
#    dest: /etc/letsencrypt/cli.ini

- name: open ports 80 and 443 through the firewall
  copy:
    src: 20-webserver
    dest: /etc/iptables/rules.d/20-webserver
  notify: reload iptables

- name: create service unit file for certificate renewal
  copy:
    src: letsencrypt-renew.service
    dest: /etc/systemd/system/letsencrypt-renew.service
  notify: reload systemd

- name: create timer unit file for certificate renewal
  copy:
    src: letsencrypt-renew.timer
    dest: /etc/systemd/system/letsencrypt-renew.timer
  notify:
  - reload systemd
  - restart letsencrypt-renew.timer

- name: start and enable letsencrypt-renew.timer
  service: name=letsencrypt-renew.timer state=started enabled=true
