---
- name: add the jessie-backports repository
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main
    state: present
    update_cache: yes
  tags: [install]

- name: install letsencrypt client
  apt: name=letsencrypt state=present default_release=jessie-backports
  tags: [install]

- name: create a webroot for letsencrypt
  file:
    path: "{{ letsencrypt_webroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
  tags: [install]

- name: configure the Alias directive in apache2 config
  template:
    src: letsencrypt.conf.j2
    dest: /etc/apache2/conf-available/letsencrypt.conf
  notify: restart apache2
  tags: [configure]

- name: enable letsencrypt.conf for apache2
  command: a2enconf letsencrypt
  args:
    creates: /etc/apache2/conf-enabled/letsencrypt.conf
  notify: restart apache2
  tags: [configure]

- name: configure letsencrypt
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
  tags: [configure]

- name: enable services http and https in firewalld
  firewalld: service={{ item }} state=enabled permanent=yes immediate=yes
  with_items: [http, https]
  tags: [serve]

- name: renew certificates monthly
  copy:
    src: letsencrypt_renew.sh
    dest: /etc/cron.monthly/letsencrypt
    mode: 0744
  tags: [serve]

#- name: request SSL certificates
#  command: letsencrypt --staging certonly
#  tags: [serve]
