---
- name: install backup
  pacman: name=backup state=present

- name: create the repository directory
  file:
    path: /var/backups
    state: directory

- name: create a directory for the LUKS keys
  file:
    path: /root/keys
    mode: 0700
    state: directory

- name: copy the LUKS keys
  copy:
    src: /root/lib/crypt/{{ item }}
    dest: /root/keys/{{ item }}
  with_items:
  - disk-backups.key
  - disk-backups2.key
  ignore_errors: yes

- name: create crypttab entries
  lineinfile:
    dest: /etc/crypttab
    line: "{{ item }}"
  with_items:
  - backups        /dev/disk/by-uuid/83b124a4-826e-4aa5-8e72-a540631cfea3   /root/keys/disk-backups.key    nofail
  - backups2       /dev/disk/by-uuid/e0bd582e-b64f-45c8-9c79-b4539bcb0039   /root/keys/disk-backups2.key   nofail
  notify: reload systemd

- name: create fstab entries
  lineinfile:
    dest: /etc/fstab
    line: "{{ item }}"
  with_items:
  - LABEL=backups  /var/backups ext3 rw,noexec,nouser,async,nodev,noauto,nosuid,nofail,x-systemd.automount 0   2
  - LABEL=backups2 /var/backups ext3 rw,noexec,nouser,async,nodev,noauto,nosuid,nofail,x-systemd.automount 0   2
  notify: reload systemd

- name: create ssh keys for root user
  command: ssh-keygen -N "" -f /root/.ssh/id_rsa
  args:
    creates: /root/.ssh/id_rsa.pub

- name: read the public key
  command: cat /root/.ssh/id_rsa.pub
  register: pubkey
  changed_when: false

#
# on the backup client:
# install ssh public keys on client with key_options: 'command="to research",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc'
# delegate to backup server to create the repository directory
# install rsync
# initialize the repository
# install the backup filter files

#- name: install the public key on the backup server
#  delegate_to: borg
#  authorized_key:
#    user: backup
#    key: "{{ pubkey.stdout }}"
#    key_options: 'command="cd /var/backups/{{ ansible_hostname }};borg serve --restrict-to-path /var/backups/{{ ansible_hostname }}",no-port-forwarding,no-X11-forwarding,no-pty,no-agent-forwarding,no-user-rc'
