---
- name: install apt-transport-https
  apt: name=apt-transport-https state=present

- name: install the InfluxDB package repository key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add the InfluxDB repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian {{ ansible_distribution_release }} stable

- name: install telegraf
  apt:
    name: telegraf
    state: present

- name: configure telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: configure statsd
  template:
    src: statsd.conf.j2
    dest: /etc/telegraf/telegraf.d/statsd.conf
  when: telegraf_inputs_statsd_enabled
  notify: restart telegraf

- include: exim.yml
  when: telegraf_inputs_exim_enabled

- include: snmp.yml
  when: telegraf_inputs_snmp_enabled

- include: opentsdb.yml
  when: telegraf_outputs_opentsdb_enabled

- name: monitor dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/telegraf/telegraf.d/dovecot.conf
  when: telegraf_inputs_dovecot_enabled
  notify: restart telegraf

- name: start and enable telegraf
  service:
    name: telegraf
    state: started
    enabled: yes
